PROFILE = awssbx
ENV = sbx
.DEFAULT_GOAL := explain
.PHONY: explain
explain:
	###
	#
	# Welcome to the AWS Infrastructure Templates repo
	#
	##

.PHONY: install
install: ## Install all the dependencies we need
	npm install

.PHONY: prepare-environment
prepare-environment: check-environment
ifeq ($(wildcard cdk.${ENV}.json),)
	@echo "[Error] cdk.${ENV}.json does not exist"
	@exit 1;
else
	cp cdk.${ENV}.json cdk.json
endif

.PHONY: check-environment
check-environment:
ifeq ($(ENV),)
	@echo "[Error] Please specify a ENV"
	@exit 1;
endif

.PHONY: deploy-stack 
deploy-stack:
	npx cdk deploy --profile $(PROFILE)


.PHONY: deploy-app-stack 
deploy-app-stack: prepare-environment
	npx cdk deploy Scout-A-ECS-APP-stack --profile $(PROFILE)

.PHONY: deploy-db-stack 
deploy-db-stack: prepare-environment
	npx cdk deploy Scout-B-ECS-DB-stack --profile $(PROFILE)